apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: orders-subscription
spec:
  topic: orders
  routes:
    default: /orders
  pubsubname: orderpubsub
  deadLetterTopic: dead-letter-orders # Optional: specify a dead-letter topic